version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: leadmap-postgres
    environment:
      POSTGRES_DB: leadmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - leadmap-postgres-data:/var/lib/postgresql/data

volumes:
  leadmap-postgres-data:
